import type { Scenario } from "@/types/game";

export const demoScenario: Scenario = {
  name: "Strait of Hormuz Standoff",
  description:
    "A US carrier strike group transits the Strait of Hormuz while Iranian naval forces patrol the coastline.",
  briefing:
    "Your carrier strike group must transit the Strait of Hormuz. Iranian fast attack craft and patrol vessels have been observed in the area. Rules of engagement: weapons tight — engage only if fired upon.",
  theater: {
    center: { lng: 56.5, lat: 26.5 },
    zoom: 7,
  },
  startTime: "2026-03-15T06:00:00Z",
  playerSide: "US Navy",
  sides: [
    {
      name: "US Navy",
      color: "#00aaff",
      isAI: false,
      units: [
        {
          id: "us-cvn-1",
          name: "USS Nimitz (CVN-68)",
          platformId: 2740,
          side: "US Navy",
          position: { lng: 57.5, lat: 25.2 },
          heading: 315,
          speed: 20,
          damageState: "undamaged",
          mission: "Transit",
        },
        {
          id: "us-cg-1",
          name: "USS Bunker Hill (CG-52)",
          platformId: 598,
          side: "US Navy",
          position: { lng: 57.3, lat: 25.3 },
          heading: 315,
          speed: 20,
          damageState: "undamaged",
          mission: "Escort",
        },
        {
          id: "us-ddg-1",
          name: "USS Mahan (DDG-72)",
          platformId: 111,
          side: "US Navy",
          position: { lng: 57.7, lat: 25.1 },
          heading: 315,
          speed: 20,
          damageState: "undamaged",
          mission: "Escort",
        },
        {
          id: "us-ddg-2",
          name: "USS Cole (DDG-67)",
          platformId: 111,
          side: "US Navy",
          position: { lng: 57.1, lat: 25.4 },
          heading: 315,
          speed: 20,
          damageState: "undamaged",
          mission: "Escort",
        },
        {
          id: "us-ffg-1",
          name: "USS Taylor (FFG-50)",
          platformId: 1283,
          side: "US Navy",
          position: { lng: 57.9, lat: 25.0 },
          heading: 315,
          speed: 18,
          damageState: "undamaged",
          mission: "ASW Screen",
        },
        {
          id: "us-fa18-1",
          name: "Hornet 101",
          platformId: 342,
          side: "US Navy",
          position: { lng: 56.8, lat: 26.0 },
          heading: 350,
          speed: 450,
          altitude: 25000,
          damageState: "undamaged",
          mission: "CAP",
        },
        {
          id: "us-fa18-2",
          name: "Hornet 102",
          platformId: 342,
          side: "US Navy",
          position: { lng: 56.6, lat: 26.1 },
          heading: 350,
          speed: 450,
          altitude: 25000,
          damageState: "undamaged",
          mission: "CAP",
        },
        {
          id: "us-e2c-1",
          name: "Hawkeye 601",
          platformId: 2471,
          side: "US Navy",
          position: { lng: 56.0, lat: 25.8 },
          heading: 270,
          speed: 280,
          altitude: 30000,
          damageState: "undamaged",
          mission: "AEW",
        },
      ],
    },
    {
      name: "Iran",
      color: "#ff4444",
      isAI: true,
      units: [
        {
          id: "ir-fac-1",
          name: "Sina 101",
          platformId: 2106,
          side: "Iran",
          position: { lng: 56.3, lat: 27.1 },
          heading: 180,
          speed: 15,
          damageState: "undamaged",
          mission: "Patrol",
        },
        {
          id: "ir-fac-2",
          name: "Sina 102",
          platformId: 2106,
          side: "Iran",
          position: { lng: 56.1, lat: 27.0 },
          heading: 200,
          speed: 15,
          damageState: "undamaged",
          mission: "Patrol",
        },
        {
          id: "ir-fac-3",
          name: "Sina 103",
          platformId: 2106,
          side: "Iran",
          position: { lng: 56.5, lat: 27.2 },
          heading: 170,
          speed: 12,
          damageState: "undamaged",
          mission: "Patrol",
        },
        {
          id: "ir-pc-1",
          name: "Kaman 201",
          platformId: 1088,
          side: "Iran",
          position: { lng: 55.8, lat: 26.8 },
          heading: 150,
          speed: 10,
          damageState: "undamaged",
          mission: "Patrol",
        },
        {
          id: "ir-pc-2",
          name: "Kaman 202",
          platformId: 1088,
          side: "Iran",
          position: { lng: 56.6, lat: 26.6 },
          heading: 220,
          speed: 10,
          damageState: "undamaged",
          mission: "Patrol",
        },
        {
          id: "ir-ff-1",
          name: "Bayandor (FF-81)",
          platformId: 1652,
          side: "Iran",
          position: { lng: 55.5, lat: 27.3 },
          heading: 160,
          speed: 12,
          damageState: "undamaged",
          mission: "Coastal Defense",
        },
        {
          id: "ir-f4-1",
          name: "Phantom 301",
          platformId: 265,
          side: "Iran",
          position: { lng: 55.0, lat: 27.5 },
          heading: 180,
          speed: 400,
          altitude: 20000,
          damageState: "undamaged",
          mission: "CAP",
        },
        {
          id: "ir-f14-1",
          name: "Tomcat 401",
          platformId: 264,
          side: "Iran",
          position: { lng: 55.3, lat: 27.8 },
          heading: 200,
          speed: 420,
          altitude: 28000,
          damageState: "undamaged",
          mission: "CAP",
        },
      ],
    },
  ],
  referencePoints: [],
};
